# Generated by Django 4.2.15 on 2024-08-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
    ]
