# Generated by Django 4.2.15 on 2024-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpAndProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Skill', models.CharField(max_length=20)),
            ],
        ),
    ]
